{% set name = "trouve" %}
{% set version = "0.6.0" %}
{% set sha256 = "1678f4b501945ce47250dc26df577a236d55d8af5acf9fceb18236817409d535" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - numpy
    - pandas
    - toolz

test:
  imports:
    - trouve

about:
  home: https://github.com/rwhitt2049/trouve
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://trouve.readthedocs.io
  dev_url: https://github.com/rwhitt2049/trouve
  summary: 'A package to search for events in time-series data that match a boolean condition.'

extra:
  recipe-maintainers:
    - rwhitt2049
