{% set name = "trouve" %}
{% set version = "0.5.1" %}
{% set sha256 = "2502b99224c9e86b75d95cc08f1bb3ea3943d15d88674839a4cda43bc2333b3a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip
    - numpy
    - pandas
    - toolz
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - toolz

test:
  imports:
    - trouve
    
about:
  home: https://github.com/rwhitt2049/trouve
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://trouve.readthedocs.io
  dev_url: https://github.com/rwhitt2049/trouve
  summary: 'A package to search for events in time-series data that match a boolean condition.'

extra:
  recipe-maintainers:
    - rwhitt2049
