travis:
  secure:
    BINSTAR_TOKEN: RXaiBzWJaUU1N/vtcWUnKCI45zLTOzA9wQQaKDfP624oNNcEDqmtqlmhxCq901q1AQc5roK3QJ8LD8eGdxpaLvGhI3JsuV0XhKptRJy4IHdymBJyMVScnNwfNkTlp1lZeseD+DGQBCYf00KeZRn2YuNgdR9SqmbcsLV8FPX9+mkzciNDckenN6hMgVxgb3cWVn19QgELH+4fjAvPrPyUhDHkWcZcDl+P/hB41F9jlmCAUZ9YurBs3jn8wwIg+yk7y+InmeU/GWHTiarpHwXBJ+1N0LScWimsYPJYN0lLeKpEfLsXqwEifU+EEZXNTqfpvqKF+JKHxWIYZrHiubbd9IoG41kIrjDngfM6lPiNloKHUYisT515b/8tJqGzC/fRI8Q0/ARU1Ml1OdboGt2cRs1vaeAH0vGx0ju1iSq7RqYzA52UhIyA44mMo8q4oOhgcuEDUBXxVnHRlmO+g42pqQBnupiFBMu//xlxMcGLKg6Qd5a7nqRkmmBkDt90smBWPm8phAFQeOzycPfnzVjAOCIFuL5ftj6CoQqFxbuUnCvYtfAh3N3FSBqJzZYfvfSHpIJeAHo0hZOtnCp4ZuDsYQ0whTQMhVSJ0WowlSXxLaEfz3HohNCbEQTZnEAOBq5u88IudAGwGGarJUAmSCujOUXdDxL6Z/EwNj71q1Aat74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
